# Generated by Django 4.0.3 on 2022-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunds',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userfunds',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userfunds',
            name='duration',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userfunds',
            name='email',
            field=models.EmailField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userfunds',
            name='order_id',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userfunds',
            name='payment_id',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='userfunds',
            name='fd_owner',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
