# Generated by Django 4.0.3 on 2022-03-25 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cust', '0002_userfunds_address_userfunds_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunds',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
