# Generated by Django 4.0.3 on 2022-03-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0011_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='cust/images/profile.jpg', upload_to=''),
        ),
    ]
